### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by ulysses4ever** [fgaz/changelog-d#2]
Fresh Cabal contributors suffer from not having a slightest idea about things like significance, description and the fact that you can use Markdown (because the output is a Markdown file). Would it be possible to add a very brief description of what can go in a changelog file (including the points I mention) to README or anywhere at all? Perhaps there’s such place already, and I just missed it?

/cc @Mikolaj

**Comment by fgaz** [comment]
Fields are described [here](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog). Maybe that section could be expanded and/or moved to this repo

**Comment by ulysses4ever** [comment]
Ah, i knew it should be somewhere. Yeah, i think it'd be preferable to move it here and link from there...

**Comment by fgaz** [comment]
I'm moving the repo, this issue is now tracked at https://codeberg.org/fgaz/changelog-d/issues/1
